### clean table auth
DELETE http://localhost:3000/auth/clean
Content-Type: application/json


### login
POST http://localhost:3000/auth/login
Content-Type: application/json

{
    "email":"antonio093@gmail.com",
    "password":"H6@kjk76mdn57h"
}

### logout
DELETE http://localhost:3000/auth/logout
Content-Type: application/json
Authorization:Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjIwYzRiYTkzLTRmYmQtNGFjMS05OTRhLWJhYjdiNDJkZWJjYSIsImlhdCI6MTczMzczNjIxOCwiZXhwIjoxNzMzNzM4MDE4fQ.ReSO_KX-rxqiDa1l-lNGu9U0taidJAoNGJJyX2H-dXc