### clean table auth
DELETE http://localhost:3000/auth/clean
Content-Type: application/json


### login
POST http://localhost:3000/auth/login
Content-Type: application/json

{
    "email":"antonio093@gmail.com",
    "password":"H6@kjd76mdn4t"
}

### logout
DELETE http://localhost:3000/auth/logout
Content-Type: application/json
Authorization:Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjQ0ODkxNDEwLTA4NTYtNGUwYy1iMWJiLTM3YzdkNWEyMmZkNSIsImlhdCI6MTczMzQ3OTExMSwiZXhwIjoxNzMzNDgwOTExfQ.Bfx0T51mJoPYATCpiPiKr3lN-St8AR9HVEz9y55OQI0