### clean table user
DELETE http://localhost:3000/user/clean
Content-Type: application/json


### register
POST http://localhost:3000/user/register
Content-Type: application/json

{
    "email":"antonio093@gmail.com",
    "password":"H6@kjk76mdn57h"
}


### update
PUT http://localhost:3000/user/update/44891410-0856-4e0c-b1bb-37c7d5a22fd5
Content-Type: application/json
Authorization:Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjQ0ODkxNDEwLTA4NTYtNGUwYy1iMWJiLTM3YzdkNWEyMmZkNSIsImlhdCI6MTczMzQ4MTIxMSwiZXhwIjoxNzMzNDgzMDExfQ.M5uVG4gZLH46vkwUMh1TnqcuoPS_WoRWPCXm-KDVkas

{
    "email":"modificato@gmail.com",
    "password":"H6@kjd768379mdn4t"
}


### delete user
DELETE http://localhost:3000/user/347aa5b1-56ad-449d-9937-ab4c012e2894
Content-Type: application/json
Authorization:Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjM0N2FhNWIxLTU2YWQtNDQ5ZC05OTM3LWFiNGMwMTJlMjg5NCIsImlhdCI6MTczMzQzMDcwNiwiZXhwIjoxNzMzNDMyNTA2fQ.7YGkN4wosqj7SLgwDCz-XATlTUJUZMd-_R_HKp5pfhA